kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
    - npm install

- name: test
  image: trion/ng-cli-karma
  commands:
    - ng test --progress false --watch false

- name: build
  image: node
  commands:
    - npm run build

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password    
    pages_directory: dist/Website