kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
    - npm install

- name: test
  image: trion/ng-cli-karma
  commands:
    - ng test --progress false --watch false

- name: build
  image: trion/ng-cli
  privileged: true
  commands:
    - npm ci
    - ng build --prod --base-href "http://github.darksilent.de/"

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password    
    pages_directory: dist/Website