kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
    - npm install
    - npm install @angular/cli

- name: test
  image: node
  commands:
    - ng test --progress false --watch false

- name: build
  image: node
  commands:
    - ng build --prod --base-href "http://github.darksilent.de/"

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password    
    pages_directory: dist/Website